pipeline:
  deploy:
    image: karappo/dronedeploy:drone-0.8
    # pull: true
    environment:
      - DEP_REMOTE_COMMAND=rsync
      - DEP_REMOTE_PORT=2222
      - DEP_REMOTE_HOST=ftp-melon-roman.heteml.net
      - DEP_REMOTE_USER=melon-roman
      - DEP_REMOTE_INCLUDE_FILE=https://raw.githubusercontent.com/karappo/drone-deploy/drone-compatible/v0.8/include-files/wordpress/.depinc.sh
      - DEP_REMOTE_IGNORE_FILE=.depignore
      #
      - DEP_MASTER_HOST_DIR=/home/users/1/melon-roman/web/melon-roman.com/
      - DEP_STAGING_HOST_DIR=/home/users/1/melon-roman/web/stg.melon-roman.com/
    commands:
      - echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - curl https://raw.githubusercontent.com/karappo/drone-deploy/drone-compatible/v0.8/deploy.sh | bash
    secrets: [ ssh_key ]
  notify:
    image: plugins/slack-blame
    token: xoxp-249440278914-250327066630-735650098996-2baebc36952f477aee942c98c9f57b63
    channel: builds-karappo
    success_template: |
      *{{build.status}}*​
      http://drone.karappo.biz/{{repo.owner}}/{{repo.name}}/{{build.number}}
      ({{build.branch}}) by {{build.author}}
    failure_template: |
      *{{build.status}}*​
      http://drone.karappo.biz/{{repo.owner}}/{{repo.name}}/{{build.number}}
      ({{build.branch}}) by {{build.author}}

